apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-app
  template:
    metadata:
      labels:
        app: vprofile-app
    spec:
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
        - name: vprofile-app
          image: moaazfarrag/app
          ports:
            - containerPort: 8080
          env:
          - name: RABBITMQ_PORT
            value: "5672"
          volumeMounts:
            - name: config-volume
              mountPath: /app/src/main/resources/application.properties
              subPath: application.properties

      volumes:
        - name: config-volume
          configMap:
            name: app-config
            items:
              - key: application.properties
                path: application.properties

